### ISSUE TITLE
nothing happens if I use the spreadsheet-tag

### ISSUE THREAD

**Issue by alFlash** [texnixe/kirby-spreadsheet#1]
Hi,
I'm trying to integrate kirby-spreadsheet.
so I downloaded the files and put them in site/plugins/kirby-spreadsheet

On my page I uploaded a simple xlsx-File `unbenannt-1.xlsx`. Then I used the new kirby-tag:

    (spreadsheet:unbenannt-1.xlsx) 
After rendering (`echo $page->text()->kirbytext()`) I only see the text: 

> (spreadsheet:unbenannt-1.xlsx)

What is my mistake? I figured out, that the plugin is loaded. The problem seems to appear at **line 18** in
`tags/spreedsheet.php`:

     $reader = new SpreadsheetReader(kirby()->roots()->content() . DS . $file->uri());

I tried also *.csv, *.ods. The same behavior...

Where is my mistake? Thank You.

Im working on kirby 2.4.1.

**Comment by texnixe** [comment]
Thanks for reporting. I can reproduce this in 2.4.1 and will look into it as soon as possible.

**Comment by alFlash** [comment]
Thank you!

**Comment by texnixe** [comment]
Should be fixed now, could you please confirm?

**Comment by alFlash** [comment]
Thank you so much! For ODS- and CSV- files it works fine.
If I try to render a XLSX (Excel-format OR open-xml-Format) this Whoops-Error appears:
    
     Whoops \ Exception \ ErrorException (E_ERROR)
     Method Kirbytext::__toString() must not throw an exception, caught Error: Call to a member function  read() on boolean 

in ` E:\xampp\htdocs\kirby2\kirby\helpers.php'

    <?php
     
      function snippet($file, $data = array(), $return = false) {
      return kirby::instance()->component('snippet')->render($file, $data, $return);
    }
     
  Thank You! André

**Comment by texnixe** [comment]
I wonder what the snippet helper has to do with that?

I tested with an .xlsx file in the first place, therefore it's hard to reproduce. If your file is nothing secret, could you provide the file for testing?

**Comment by alFlash** [comment]
[Unbenannt 4.txt](https://github.com/texnixe/kirby-spreadsheet/files/730691/Unbenannt.4.txt)
Here it is. I renamed it from **xlsx** to **txt**

**Comment by texnixe** [comment]
Thank you, André. When I tried to use this file, I got the same error, but then I added a line and removed it again and then saved again, and then the file worked. So I guess, something made the file unreadable, but I can't tell what nor do I have an idea what to do about it…:thinking:

**Comment by alFlash** [comment]
Maybe my LibreOffice produces these mistakes. No matter... So everything is solved! Great. Thank you! You are very helpful. Ich danke Dir herzlich. André

**Comment by texnixe** [comment]
I'll try to test if I get the same problem with LibreOffice (I'm not on Windows though)
